name: Hotfix

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version to fix'
        required: true

jobs:
  hotfix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: releases/${{ github.event.inputs.release_version }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Run linter and tests
        run: |
          npm ci
          npm run lint
          npm run test
          
      - name: Build and push Docker image
        run: |
          docker build . -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_fix${{ github.run_number }} \
                         -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_latest
          docker login -u iam -p ${{ secrets.YC_IAM_TOKEN }} cr.yandex
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_fix${{ github.run_number }}
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_latest
          
      - name: Create fix tag
        run: |
          git tag -a v${{ github.event.inputs.release_version }}_fix${{ github.run_number }} -m "Hotfix for release ${{ github.event.inputs.release_version }}"
          git push origin v${{ github.event.inputs.release_version }}_fix${{ github.run_number }}
          
      - name: Add fix comment to issue
        run: |
          gh issue comment ${{ github.event.inputs.issue_number}} --body "Hotfix applied:\n- Date: $(date)\n- Author: ${{ github.actor }}\n- Fix version: ${{ github.run_number }}\n- Docker image: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_fix${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}